// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: boards.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBoard = `-- name: CreateBoard :one
WITH new_board AS (
    INSERT INTO boards (
            id,
            user_id,
            title,
            created_at,
            updated_at
        )
    VALUES (
            gen_random_uuid(),
            $1,
            $2,
            NOW(),
            NOW()
        )
    RETURNING id, user_id, title, created_at, updated_at
),
default_columns AS (
    INSERT INTO board_columns (
            id,
            board_id,
            title,
            position,
            created_at,
            updated_at
        )
    SELECT gen_random_uuid(),
        new_board.id,
        col.title,
        col.position,
        NOW(),
        NOW()
    FROM new_board
        JOIN (
            VALUES ('Todo', 1),
                ('In Progress', 2),
                ('Done', 3)
        ) AS col(title, position) ON TRUE
)
SELECT id, user_id, title, created_at, updated_at
FROM new_board
`

type CreateBoardParams struct {
	UserID uuid.UUID
	Title  string
}

type CreateBoardRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (CreateBoardRow, error) {
	row := q.db.QueryRowContext(ctx, createBoard, arg.UserID, arg.Title)
	var i CreateBoardRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBoard = `-- name: DeleteBoard :exec
DELETE FROM boards
WHERE id = $1
`

func (q *Queries) DeleteBoard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBoard, id)
	return err
}

const getBoard = `-- name: GetBoard :one
SELECT b.id,
    b.user_id,
    b.title,
    b.created_at,
    b.updated_at,
    COALESCE(
        json_agg(
            jsonb_build_object(
                'id',
                bc.id,
                'title',
                bc.title,
                'position',
                bc.position,
                'created_at',
                bc.created_at,
                'updated_at',
                bc.updated_at,
                'cards',
                COALESCE(bc.cards, '[]'::json)
            )
            ORDER BY bc.position
        ) FILTER (
            WHERE bc.id IS NOT NULL
        ),
        '[]'::json
    ) AS columns
FROM boards b
    LEFT JOIN (
        SELECT c.id,
            c.board_id,
            c.title,
            c.position,
            c.created_at,
            c.updated_at,
            json_agg(
                jsonb_build_object(
                    'id',
                    ca.id,
                    'title',
                    ca.title,
                    'description',
                    ca.description,
                    'position',
                    ca.position,
                    'created_at',
                    ca.created_at,
                    'updated_at',
                    ca.updated_at
                )
                ORDER BY ca.position
            ) FILTER (
                WHERE ca.id IS NOT NULL
            ) AS cards
        FROM board_columns c
            LEFT JOIN cards ca ON ca.column_id = c.id
        GROUP BY c.id
    ) bc ON bc.board_id = b.id
WHERE b.id = $1
GROUP BY b.id
`

type GetBoardRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     string
	CreatedAt time.Time
	UpdatedAt time.Time
	Columns   interface{}
}

func (q *Queries) GetBoard(ctx context.Context, id uuid.UUID) (GetBoardRow, error) {
	row := q.db.QueryRowContext(ctx, getBoard, id)
	var i GetBoardRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Columns,
	)
	return i, err
}

const getBoardByID = `-- name: GetBoardByID :one
SELECT id, user_id, title, created_at, updated_at
FROM boards
WHERE id = $1
`

func (q *Queries) GetBoardByID(ctx context.Context, id uuid.UUID) (Board, error) {
	row := q.db.QueryRowContext(ctx, getBoardByID, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBoardsForUser = `-- name: GetBoardsForUser :many
SELECT id, user_id, title, created_at, updated_at
FROM boards
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) GetBoardsForUser(ctx context.Context, userID uuid.UUID) ([]Board, error) {
	rows, err := q.db.QueryContext(ctx, getBoardsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Board
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isBoardOwner = `-- name: IsBoardOwner :one
SELECT EXISTS (
        SELECT 1
        FROM boards
        WHERE id = $1
            AND user_id = $2
    )
`

type IsBoardOwnerParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) IsBoardOwner(ctx context.Context, arg IsBoardOwnerParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isBoardOwner, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateBoard = `-- name: UpdateBoard :one
UPDATE boards
SET title = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, title, created_at, updated_at
`

type UpdateBoardParams struct {
	ID    uuid.UUID
	Title string
}

func (q *Queries) UpdateBoard(ctx context.Context, arg UpdateBoardParams) (Board, error) {
	row := q.db.QueryRowContext(ctx, updateBoard, arg.ID, arg.Title)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
