// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: boards.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBoard = `-- name: CreateBoard :one
WITH new_board AS (
    INSERT INTO boards (
        id,
        user_id,
        title,
        created_at,
        updated_at
    )
    VALUES (
        gen_random_uuid(),
        $1,            -- user_id
        $2,            -- board title
        NOW(),
        NOW()
    )
    RETURNING id, user_id, title, created_at, updated_at
),
default_columns AS (
    INSERT INTO board_columns (
        id,
        board_id,
        title,
        position,
        created_at,
        updated_at
    )
    SELECT
        gen_random_uuid(),
        new_board.id,
        col.title,
        col.position,
        NOW(),
        NOW()
    FROM new_board
    JOIN (
        VALUES
            ('Todo', 1),
            ('In Progress', 2),
            ('Done', 3)
    ) AS col(title, position)
    ON TRUE
)
SELECT
    id,
    user_id,
    title,
    created_at,
    updated_at
FROM new_board
`

type CreateBoardParams struct {
	UserID uuid.UUID
	Title  string
}

type CreateBoardRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (CreateBoardRow, error) {
	row := q.db.QueryRowContext(ctx, createBoard, arg.UserID, arg.Title)
	var i CreateBoardRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBoardByID = `-- name: GetBoardByID :one
SELECT
    b.id,
    b.user_id,
    b.title,
    b.created_at,
    b.updated_at,

    COALESCE(
        JSON_AGG(
            DISTINCT JSONB_BUILD_OBJECT(
                'id', c.id,
                'title', c.title,
                'position', c.position,
                'created_at', c.created_at,
                'updated_at', c.updated_at,
                'cards', COALESCE(cards.cards, '[]'::json)
            )
            ORDER BY c.position
        ) FILTER (WHERE c.id IS NOT NULL),
        '[]'
    ) AS columns

FROM boards b
LEFT JOIN board_columns c
    ON c.board_id = b.id

LEFT JOIN LATERAL (
    SELECT
        JSON_AGG(
            JSONB_BUILD_OBJECT(
                'id', cd.id,
                'title', cd.title,
                'description', cd.description,
                'position', cd.position,
                'created_at', cd.created_at,
                'updated_at', cd.updated_at
            )
            ORDER BY cd.position
        ) AS cards
    FROM cards cd
    WHERE cd.column_id = c.id
) cards ON TRUE

WHERE b.id = $1
GROUP BY b.id
`

type GetBoardByIDRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     string
	CreatedAt time.Time
	UpdatedAt time.Time
	Columns   interface{}
}

func (q *Queries) GetBoardByID(ctx context.Context, id uuid.UUID) (GetBoardByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getBoardByID, id)
	var i GetBoardByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Columns,
	)
	return i, err
}
