// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCard = `-- name: CreateCard :one
INSERT INTO cards (id, column_id, title, description, position)
VALUES (
        gen_random_uuid(),
        $1,
        $2,
        $3,
        $4
    )
RETURNING id, column_id, title, description, position, created_at, updated_at
`

type CreateCardParams struct {
	ColumnID    uuid.UUID
	Title       string
	Description sql.NullString
	Position    float64
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, createCard,
		arg.ColumnID,
		arg.Title,
		arg.Description,
		arg.Position,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM cards
WHERE id = $1
`

func (q *Queries) DeleteCard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCard, id)
	return err
}

const getCard = `-- name: GetCard :one
SELECT id, column_id, title, description, position, created_at, updated_at
FROM cards
where id = $1
`

func (q *Queries) GetCard(ctx context.Context, id uuid.UUID) (Card, error) {
	row := q.db.QueryRowContext(ctx, getCard, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCardsForColumn = `-- name: GetCardsForColumn :many
SELECT id, column_id, title, description, position, created_at, updated_at
FROM cards
WHERE column_id = $1
ORDER BY position ASC
`

func (q *Queries) GetCardsForColumn(ctx context.Context, columnID uuid.UUID) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, getCardsForColumn, columnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.ColumnID,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isCardOwner = `-- name: IsCardOwner :one
SELECT EXISTS (
        SELECT 1
        FROM cards c
            JOIN board_columns bc ON bc.id = c.column_id
            JOIN boards b ON b.id = bc.board_id
        WHERE c.id = $1
            AND b.user_id = $2
    )
`

type IsCardOwnerParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) IsCardOwner(ctx context.Context, arg IsCardOwnerParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isCardOwner, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateCard = `-- name: UpdateCard :one
UPDATE cards
SET title = $2,
    description = $3,
    position = $4,
    column_id = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, column_id, title, description, position, created_at, updated_at
`

type UpdateCardParams struct {
	ID          uuid.UUID
	Title       string
	Description sql.NullString
	Position    float64
	ColumnID    uuid.UUID
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, updateCard,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Position,
		arg.ColumnID,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
