// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCard = `-- name: CreateCard :one
INSERT INTO cards (id, column_id, title, description, position)
VALUES (
        gen_random_uuid(),
        $1,
        $2,
        $3,
        $4
    )
RETURNING id, column_id, title, description, position, created_at, updated_at
`

type CreateCardParams struct {
	ColumnID    uuid.UUID
	Title       string
	Description sql.NullString
	Position    int32
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, createCard,
		arg.ColumnID,
		arg.Title,
		arg.Description,
		arg.Position,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isCardOwner = `-- name: IsCardOwner :one
SELECT EXISTS (
        SELECT 1
        FROM cards c
            JOIN board_columns bc ON bc.id = c.column_id
            JOIN boards b ON b.id = bc.board_id
        WHERE c.id = $1
            AND b.user_id = $2
    )
`

type IsCardOwnerParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) IsCardOwner(ctx context.Context, arg IsCardOwnerParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isCardOwner, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
