// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: columns.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const isColumnOwner = `-- name: IsColumnOwner :one
SELECT EXISTS (
        SELECT 1
        FROM board_columns bc
            JOIN boards b ON b.id = bc.board_id
        WHERE bc.id = $1
            AND b.user_id = $2
    )
`

type IsColumnOwnerParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) IsColumnOwner(ctx context.Context, arg IsColumnOwnerParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isColumnOwner, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
