name: Bug
description: Track and fix a bug completely
title: "[Bug] "
labels:
  - bug
projects: ["mrbrist/8"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What’s broken
      description: What is happening that shouldn’t be?
      placeholder: Briefly describe the bug
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: How to reproduce
      description: Minimal steps to see the bug
      placeholder: |
        1. Go to...
        2. Click...
        3. See error
    validations:
      required: true
